apiVersion: apps/v1
kind: Deployment
metadata:
  name: scheduler
  labels:
    {{- include "scheduler.labels" . | nindent 4}}
    app.kubernetes.io/component: scheduler
spec:
  replicas: {{ .Values.scheduler.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: scheduler
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: scheduler
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      terminationGracePeriodSeconds: 0
      containers:
        - name: scheduler
          image: {{ .Values.scheduler.image }}
          env:
            - name: DB_URL
              valueFrom:
                secretKeyRef:
                  name: mongodb
                  key: scheduler_db_url 
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          readinessProbe:
            initialDelaySeconds: 10
            periodSeconds: 1
            httpGet:
              path: /
              port: 3000
          livenessProbe:
            initialDelaySeconds: 10
            periodSeconds: 1
            httpGet:
              path: /
              port: 3000