apiVersion: v1
kind: Secret
metadata:
  name: mongodb
  labels:
    app.kubernetes.io/component: mongodb
    {{- include "scheduler.labels" . | nindent 4}}
type: Opaque
data:
  scheduler_db_url: {{ .Values.schedulerMongoUrl | b64enc }}